import { useEffect, useRef, useState, type ReactNode } from 'react';
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Briefcase, Check, ChevronDown, ChevronLeft, ChevronRight, Clapperboard, Code2, Download, ExternalLink, FileText, Github, Linkedin, Mail, Menu, Pause, Play, SkipForward, Sparkles, VolumeX, X } from 'lucide-react';
import { profile, projects, journey, skillGroups, modes, introScenes, type Project, type ViewMode, type SectionId } from './data/portfolio';

const curve = [0.22, 1, 0.36, 1] as const;
const reveal = { initial: { opacity: 0, y: 42, filter: 'blur(8px)' }, whileInView: { opacity: 1, y: 0, filter: 'blur(0px)' }, viewport: { once: true, amount: 0.15 }, transition: { duration: 0.85, ease: curve } };
const imageRemote = 'https://raw.githubusercontent.com/jatin45ppandey-design/jatin45ppandey-design/main/assets/profile-photo.jpg';
function Portrait({ className = '', style = {} }: { className?: string; style?: React.CSSProperties }) {
  return <img src={imageRemote} className={className} style={style} alt="Portrait of Jatin Pandey" loading="eager" onError={e => { e.currentTarget.style.display = 'none'; }} />;
}
function Label({ children }: { children: ReactNode }) { return <span className="eyebrow"><span className="eyebrow-line" />{children}</span>; }
function SectionHeading({ kicker, title, subtitle }: { kicker: string; title: string; subtitle?: string }) {
  return <motion.div {...reveal} className="section-heading"><Label>{kicker}</Label><h2 className="display">{title}</h2>{subtitle && <p className="section-subtitle">{subtitle}</p>}</motion.div>;
}
function ButtonLink({ href, children, variant = 'outline' }: { href: string; children: ReactNode; variant?: 'outline' | 'gold' }) { return <a className={'button ' + (variant === 'gold' ? 'button-gold' : 'button-outline')} href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={16} /></a>; }

function Opening({ done }: { done: () => void }) {
  const reduced = useReducedMotion();
  const [beat, setBeat] = useState(reduced ? 5 : 0);
  useEffect(() => {
    if (reduced) return;
    const timers = [400, 1450, 2600, 3800, 4800].map((ms, i) => window.setTimeout(() => setBeat(i + 1), ms));
    return () => timers.forEach(clearTimeout);
  }, [reduced]);
  useEffect(() => {
    const key = (e: KeyboardEvent) => { if (e.key === 'Escape' || e.key === 'Enter') done(); };
    window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key);
  }, [done]);
  return <motion.div className="opening" exit={{ opacity: 0, scale: 1.04, filter: 'blur(12px)' }} transition={{ duration: .8 }} role="dialog" aria-label="Opening sequence">
    <div className="opening-ambient" />
    <div className="film-bar film-top"/><div className="film-bar film-bottom"/>
    <AnimatePresence>{beat === 1 && <motion.div className="studio-title" initial={{ opacity: 0, letterSpacing: '.7em' }} animate={{ opacity: 1, letterSpacing: '.38em' }} exit={{ opacity: 0 }} transition={{ duration: 0.8 }}>A JATIN ORIGINAL</motion.div>}</AnimatePresence>
    <motion.div className="opening-portrait" initial={{ opacity: 0, scale: 1.13, filter: 'blur(20px) grayscale(1)' }} animate={beat >= 3 ? { opacity: .65, scale: 1, filter: 'blur(0px) grayscale(.35)' } : {}} transition={{ duration: 1.5, ease: curve }}><Portrait /></motion.div>
    <motion.div className="opening-brand" initial={{ opacity: 0, scale: 1.1, filter: 'blur(18px)' }} animate={beat >= 2 ? { opacity: 1, scale: 1, filter: 'blur(0px)' } : {}} transition={{ duration: 1.2, ease: curve }}>
      <div className="opening-name">JATIN</div><motion.div className="opening-series" animate={{ opacity: beat >= 3 ? 1 : 0 }}>— THE SERIES —</motion.div>
    </motion.div>
    <motion.div className="opening-action" animate={{ opacity: beat >= 4 ? 1 : 0, y: beat >= 4 ? 0 : 18 }} transition={{ duration: .6 }}>
      <p>BEYOND THE CODE. BEHIND THE CREATION.</p><button className="button button-gold" onClick={done} tabIndex={beat >= 4 ? 0 : -1}><Play size={16} fill="currentColor" /> ENTER THE SERIES</button>
    </motion.div>
    <button className="skip-intro" onClick={done}><SkipForward size={15}/> SKIP INTRO</button>
  </motion.div>;
}
function Selector({ choose }: { choose: (id: ViewMode) => void }) {
  return <motion.div className="selector" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, scale: 1.04, filter: 'blur(10px)' }} transition={{ duration: .65 }} role="dialog" aria-label="Choose your perspective">
    <div className="selector-light"/><Label>WELCOME TO THE SERIES</Label><h2 className="selector-title">Who's exploring?</h2><p className="muted">One developer. Three ways to experience the story.</p>
    <div className="selector-cards">{modes.map((m,i) => <motion.button key={m.id} className="selector-card" initial={{ opacity: 0, y: 34 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .13 * i, duration: .7, ease: curve }} onClick={() => choose(m.id)}>
      <div className={'selector-art selector-' + m.id}><span className="selector-index">0{i+1}</span>{m.id === 'explore' ? <Clapperboard size={54} strokeWidth={1}/> : m.id === 'recruiter' ? <Briefcase size={54} strokeWidth={1}/> : <Code2 size={54} strokeWidth={1} />}<span className="selector-art-title">{m.eyebrow}</span></div>
      <span className="selector-card-title">{m.title}</span><span className="selector-description">{m.description}</span>
    </motion.button>)}</div>
    <button className="selector-skip" onClick={() => choose('explore')}>JUST EXPLORE <ArrowRight size={14}/></button>
  </motion.div>;
}
function Nav({ mode, switchMode, replay }: { mode: ViewMode; switchMode: (m: ViewMode) => void; replay: () => void }) {
  const [menu, setMenu] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const handler = () => setScrolled(window.scrollY > 70); window.addEventListener('scroll', handler, { passive: true }); return () => window.removeEventListener('scroll', handler); }, []);
  return <header className={'navbar ' + (scrolled ? 'navbar-scrolled' : '')}><a href="#home" className="brandmark">J<span className="gold">.</span><small>THE SERIES</small></a>
    <nav className={'navlinks ' + (menu ? 'navlinks-open' : '')} aria-label="Main navigation">
      {([['#about','About'],['#originals','Originals'],['#journey','Journey'],['#skills','Skills'],['#highlights','Highlights'],['#dossier','Resume']] as const).map(([href,label]) => <a key={href} href={href} onClick={() => setMenu(false)}>{label}</a>)}
      <button onClick={replay} className="nav-replay">REPLAY INTRO</button>
    </nav>
    <div className="nav-right"><label className="mode-switch-label" htmlFor="mode-select">VIEW</label><select id="mode-select" className="mode-select" value={mode} onChange={e => switchMode(e.target.value as ViewMode)} aria-label="Change viewing mode">{modes.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select><button className="menu-toggle" aria-label={menu ? 'Close menu' : 'Open menu'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X size={22}/> : <Menu size={22}/>}</button></div>
  </header>;
}
function Hero({ onIntro, onWork, onResume, mode }: { onIntro: () => void; onWork: () => void; onResume: () => void; mode: ViewMode }) {
  const ref = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end start'] });
  const portraitY = useTransform(scrollYProgress, [0, 1], ['0%','17%']); const copyY = useTransform(scrollYProgress,[0,1],['0%','-20%']); const fade = useTransform(scrollYProgress,[0,.86],[1,0]);
  return <section className="hero" id="home" ref={ref}><div className="hero-glow"/><div className="hero-orbit"/>
    <motion.div className="hero-photo" style={{ y: portraitY, opacity: fade }}><div className="portrait-halo"/><Portrait /><div className="portrait-grade"/></motion.div>
    <div className="hero-readability"/><motion.div className="hero-copy" style={{ y:copyY,opacity:fade }}><motion.div initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.2}}><Label>A DEVELOPER ORIGINAL</Label></motion.div>
      <motion.h1 initial={{opacity:0,y:35,filter:'blur(12px)'}} animate={{opacity:1,y:0,filter:'blur(0px)'}} transition={{duration:1,ease:curve,delay:.35}}>JATIN<span className="hero-series">THE SERIES</span></motion.h1>
      <motion.p className="hero-role" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.6}}>BACKEND-FOCUSED DEVELOPER <span>·</span> JAVA <span>·</span> SPRING BOOT</motion.p>
      <motion.p className="hero-description" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.72}}>{profile.description}</motion.p>
      <motion.div className="hero-actions" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.85}}><button className="button button-gold" onClick={onIntro}><Play size={16} fill="currentColor"/> PLAY INTRO</button><button className="button button-outline" onClick={mode === 'recruiter' ? onResume : onWork}>{mode === 'recruiter' ? 'VIEW RESUME' : 'EXPLORE WORK'}<ArrowUpRight size={16}/></button></motion.div>
      <motion.div className="hero-meta" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:1.1}}><span>INDIA</span><span className="meta-dot"/><span>SOFTWARE ENGINEERING</span><span className="meta-dot"/><span>THREE ORIGINALS</span></motion.div>
    </motion.div><a className="scroll-cue" href="#about"><span>SCROLL TO EXPLORE</span><ArrowDown size={17}/></a>
  </section>;
}
function About() { return <section id="about" className="section about-section"><SectionHeading kicker="EPISODE 00 / THE PILOT" title="THE PERSON BEHIND THE CODE."/><div className="about-grid"><motion.div {...reveal} className="about-lead">Great software starts with <em>curiosity.</em><span className="about-rule"/></motion.div><motion.div {...reveal} className="about-copy"><p>I'm <strong>Jatin Pandey</strong>, a backend-focused developer passionate about building practical, meaningful software. I enjoy turning ideas into working products and understanding the systems that power them.</p><p>My interests span backend development, Java and Spring Boot, database architecture, and AI-assisted tools that solve real problems.</p><div className="about-signature">BUILDING <span>·</span> LEARNING <span>·</span> IMPROVING</div></motion.div></div></section>; }
function Journey() { return <section id="journey" className="section journey-section"><SectionHeading kicker="THE STORY SO FAR" title="MY JOURNEY" subtitle="Every developer has an origin story. These are the chapters I'm writing."/><div className="journey-list">{journey.map((j,i)=><motion.article className="episode" key={j.code} {...reveal}><div className="episode-number">{String(i+1).padStart(2,'0')}</div><div className="episode-art"><span>{j.code}</span><div className="episode-art-number">{String(i+1).padStart(2,'0')}</div></div><div className="episode-text"><div className="micro gold">{j.label}</div><h3>{j.title}</h3><p>{j.text}</p><div className="tags">{j.tags.map(t=><span key={t}>{t}</span>)}</div></div><ArrowUpRight size={20} className="episode-arrow"/></motion.article>)}</div></section>; }

function PosterArt({ project, large = false }: { project: Project; large?: boolean }) {
  return <div className={'poster poster-' + project.palette + (large ? ' poster-large' : '')}><div className="poster-grain"/><span className="poster-top">A JATIN ORIGINAL <span>{project.number} / 03</span></span><div className="poster-visual">{project.id === 'bhumiai' ? <div className="poster-document"><div className="paper-head"/><div className="paper-row"/><div className="paper-row short"/><div className="paper-row"/><div className="paper-stamp">✓</div><div className="paper-row short"/></div> : project.id === 'codesense' ? <div className="poster-code"><span>{'{ }'}</span><div className="code-orbit orbit-one"/><div className="code-orbit orbit-two"/><div className="code-orbit orbit-three"/></div> : <div className="poster-payment"><span>PV / 26</span><div className="payment-chip"/><span className="payment-waves">)))</span><div className="payment-dots">•••• &nbsp; •••• &nbsp; 2046</div></div>}</div><div className="poster-bottom"><span className="poster-subtitle">{project.eyebrow}</span><h3>{project.title}</h3><span className="poster-genre">{project.genre}</span><span className="poster-link">EXPLORE ORIGINAL <ArrowUpRight size={13}/></span></div></div>;
}
function Originals({ onSelect }: { onSelect: (p: Project) => void }) {
  return <section className="section originals-section" id="originals"><div className="originals-heading"><SectionHeading kicker="FEATURED PRODUCTIONS / 2026" title="THE ORIGINALS" subtitle="Real problems. Thoughtful engineering. Three productions with more stories to come."/><span className="rail-instruction">SCROLL OR SWIPE TO EXPLORE <ArrowRight size={16}/></span></div><div className="poster-rail">{projects.map((p,i)=><motion.button type="button" key={p.id} className="poster-frame" onClick={() => onSelect(p)} initial={{opacity:0,y:48}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.7,delay:i*.11,ease:curve}} aria-label={'Explore '+p.title}><PosterArt project={p}/></motion.button>)}<a href={profile.github} className="poster-more" target="_blank" rel="noreferrer"><Github size={34} strokeWidth={1}/><span>MORE ON<br/>GITHUB</span><ArrowUpRight size={19}/></a></div></section>;
}
function Skills({ openProject }: { openProject: (p: Project) => void }) {
  const [active,setActive]=useState<string|null>(null);
  return <section className="section skills-section" id="skills"><SectionHeading kicker="BEHIND EVERY BUILD" title="THE ARSENAL" subtitle="Technologies have a purpose. Explore how each one connects to real work."/><div className="skill-grid">{skillGroups.map(g=><motion.div {...reveal} className="skill-group" key={g.index}><div className="skill-group-top"><span className="micro gold">{g.index} / TECHNOLOGIES</span><Sparkles size={18}/></div><h3>{g.title}</h3><p>{g.description}</p><div className="skill-chips">{g.skills.map(s=><button key={s.name} className={'skill-chip '+(active === s.name?'selected':'')} onClick={()=>setActive(active===s.name?null:s.name)} aria-pressed={active===s.name}>{s.name}</button>)}</div><AnimatePresence>{g.skills.filter(s=>s.name===active).map(s=><motion.div key={s.name} className="skill-context" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><span>USED IN</span><strong>{s.project}</strong>{projects.find(p=>s.project.includes(p.title))&&<button onClick={()=>openProject(projects.find(p=>s.project.includes(p.title))!)}>EXPLORE <ArrowUpRight size={13}/></button>}</motion.div>)}</AnimatePresence></motion.div>)}</div></section>;
}
function Highlights({ openProject }: { openProject: (p: Project) => void }) { return <section className="section highlights-section" id="highlights"><SectionHeading kicker="MILESTONES & RECOGNITION" title="THE HIGHLIGHTS" subtitle="The work so far — with the story still unfolding."/><div className="highlights-grid">{projects.map((p,i)=><motion.button className={'highlight-card highlight-'+p.palette} key={p.id} {...reveal} onClick={()=>openProject(p)}><div className="highlight-top"><span>BUILD MILESTONE / 0{i+1}</span><Sparkles size={20}/></div><div className="highlight-symbol">{p.id==='bhumiai'?'B':p.id==='codesense'?'C':'P'}</div><div className="highlight-bottom"><span>FEATURED PROJECT</span><h3>{p.title}</h3><p>{p.logline}</p><ArrowUpRight size={19}/></div></motion.button>)}</div><p className="honesty-note"><Check size={15}/> Verified awards and certifications will be added here when supporting details are provided. No invented credentials.</p></section>; }
function Dossier({ onView }: { onView: () => void }) { return <section className="section dossier-section" id="dossier"><div className="dossier-grid"><motion.div {...reveal}><SectionHeading kicker="THE OFFICIAL DOSSIER" title="THE STORY, ON PAPER." subtitle="Professional information, in one place. The resume viewer will be enabled once the actual PDF is provided."/><div className="dossier-actions"><button className="button button-gold" onClick={onView}><FileText size={17}/> {profile.resumePdf?'VIEW RESUME':'RESUME DETAILS'}</button>{profile.resumePdf&&<ButtonLink href={profile.resumePdf}><Download size={17}/> DOWNLOAD PDF</ButtonLink>}</div></motion.div><motion.div {...reveal} className="resume-sheet"><div className="resume-head"><span>JP<span className="gold">.</span></span><small>THE OFFICIAL DOSSIER</small></div><h3>JATIN<br/>PANDEY</h3><p>BACKEND-FOCUSED DEVELOPER</p><div className="resume-line"/><span className="sheet-label">PROFILE</span><p className="sheet-text">Java / Spring Boot / PostgreSQL</p><span className="sheet-label">FEATURED WORK</span><p className="sheet-text">BhumiAI · CodeSense · PayVia</p><span className="sheet-label">EDUCATION</span><p className="sheet-text">B.Tech · Computer Science & Engineering</p><span className="resume-watermark">JP</span></motion.div></div></section>; }
function FinalCTA({ replay }: { replay: () => void }) { return <footer className="footer" id="contact"><div className="footer-glow"/><Label>THE STORY CONTINUES</Label><h2 className="display footer-title">TO BE<br/><span>CONTINUED.</span></h2><p>Have an idea worth building? Let's make something useful.</p><div className="footer-actions"><ButtonLink href={'mailto:'+profile.email} variant="gold"><Mail size={17}/> SAY HELLO</ButtonLink><ButtonLink href={profile.github}><Github size={17}/> GITHUB</ButtonLink><ButtonLink href={profile.linkedin}><Linkedin size={17}/> LINKEDIN</ButtonLink></div><div className="footer-bottom"><span>© {new Date().getFullYear()} JATIN PANDEY</span><button onClick={replay}><Clapperboard size={14}/> REPLAY THE SERIES</button><span>BUILT WITH PURPOSE.</span></div></footer>; }
function ProjectModal({ project, close, change }: { project: Project; close: () => void; change: (p: Project) => void }) {
  const position=projects.findIndex(p=>p.id===project.id);
  useEffect(() => {
    const before=document.body.style.overflow; document.body.style.overflow='hidden';
    const key=(e:KeyboardEvent)=>{ if(e.key==='Escape')close(); if(e.key==='ArrowRight')change(projects[(position+1)%projects.length]); if(e.key==='ArrowLeft')change(projects[(position+projects.length-1)%projects.length]); };
    window.addEventListener('keydown',key); return()=>{document.body.style.overflow=before;window.removeEventListener('keydown',key);};
  },[close,change,position]);
  return <motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true" aria-label={project.title+' project details'} onClick={close}><motion.div className="project-modal" initial={{scale:.94,y:45,opacity:0}} animate={{scale:1,y:0,opacity:1}} exit={{scale:.98,y:30,opacity:0}} transition={{duration:.5,ease:curve}} onClick={e=>e.stopPropagation()} key={project.id}><div className="modal-toolbar"><span className="micro gold">JATIN ORIGINAL / {project.number}</span><button aria-label="Close project" onClick={close}><X size={22}/></button></div><div className="modal-hero"><PosterArt project={project} large/><div className="modal-intro"><Label>{project.genre}</Label><h2 className="display">{project.title}</h2><p className="modal-logline">{project.logline}</p><p>{project.description}</p><div className="tags">{project.stack.map(s=><span key={s}>{s}</span>)}</div><div className="modal-actions">{project.github&&<ButtonLink variant="gold" href={project.github}><Github size={16}/> VIEW SOURCE</ButtonLink>}{project.demo&&<ButtonLink href={project.demo}><ExternalLink size={16}/> LIVE DEMO</ButtonLink>}</div><span className="micro gold">SCROLL FOR THE FULL STORY <ChevronDown size={12}/></span></div></div><div className="modal-details"><div><span className="micro gold">01 / THE PLOT</span><h3>The problem</h3><p>{project.problem}</p></div><div><span className="micro gold">02 / THE SOLUTION</span><h3>The approach</h3><p>{project.solution}</p></div><div><span className="micro gold">03 / KEY SCENES</span><h3>What it does</h3><ul>{project.features.map(f=><li key={f}>{f}</li>)}</ul></div><div><span className="micro gold">04 / BEHIND THE BUILD</span><h3>Engineering notes</h3><ul>{project.engineering.map(f=><li key={f}>{f}</li>)}</ul></div></div><div className="modal-switch"><button onClick={()=>change(projects[(position+projects.length-1)%projects.length])}><ChevronLeft size={19}/> PREVIOUS ORIGINAL</button><span>{position+1} / {projects.length}</span><button onClick={()=>change(projects[(position+1)%projects.length])}>NEXT ORIGINAL <ChevronRight size={19}/></button></div></motion.div></motion.div>;
}
function IntroReel({ close }: { close:()=>void }) {
  const [slide,setSlide]=useState(0);const [paused,setPaused]=useState(false);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='ArrowRight')setSlide(n=>(n+1)%introScenes.length);if(e.key==='ArrowLeft')setSlide(n=>(n+introScenes.length-1)%introScenes.length);if(e.code==='Space'){e.preventDefault();setPaused(v=>!v);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[close]);
  useEffect(()=>{if(paused)return;const interval=window.setInterval(()=>setSlide(n=>(n+1)%introScenes.length),4500);return()=>window.clearInterval(interval);},[paused]);
  useEffect(()=>{const before=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=before;};},[]);
  const scene=introScenes[slide];return <motion.div className="reel" role="dialog" aria-modal="true" aria-label="Play introduction" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="reel-light"/><div className="reel-top"><span>A JATIN ORIGINAL / HIGHLIGHT REEL</span><button onClick={close} aria-label="Close intro"><X size={23}/></button></div><div className="reel-bars">{introScenes.map((_,i)=><button key={i} onClick={()=>setSlide(i)} aria-label={'Go to scene '+(i+1)}><span className={i<=slide?'filled':''}/></button>)}</div><AnimatePresence mode="wait"><motion.div className="reel-content" key={slide} initial={{opacity:0,filter:'blur(16px)',scale:1.05}} animate={{opacity:1,filter:'blur(0)',scale:1}} exit={{opacity:0,filter:'blur(12px)',scale:.96}} transition={{duration:.65}}><Label>{scene.kicker}</Label><h2 className="display">{scene.title}</h2><p>{scene.note}</p></motion.div></AnimatePresence><div className="reel-controls"><button onClick={()=>setSlide(n=>(n+introScenes.length-1)%introScenes.length)} aria-label="Previous scene"><ArrowLeft/></button><button onClick={()=>setPaused(!paused)} aria-label={paused?'Play':'Pause'}>{paused?<Play/>:<Pause/>}</button><button onClick={()=>setSlide(n=>(n+1)%introScenes.length)} aria-label="Next scene"><ArrowRight/></button><span><VolumeX size={15}/> MUTED</span></div></motion.div>;
}
function ResumeModal({close}:{close:()=>void}) { useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[close]);return <motion.div className="modal-backdrop resume-overlay" role="dialog" aria-modal="true" aria-label="Resume information" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}><div className="resume-modal" onClick={e=>e.stopPropagation()}><button className="resume-close" onClick={close} aria-label="Close resume"><X/></button>{profile.resumePdf?<><h2>THE OFFICIAL DOSSIER</h2><iframe title="Jatin Pandey Resume" src={profile.resumePdf}/><ButtonLink href={profile.resumePdf} variant="gold">DOWNLOAD PDF <Download size={16}/></ButtonLink></>:<><FileText size={40} color="#D6B57A"/><Label>THE OFFICIAL DOSSIER</Label><h2>Resume coming soon.</h2><p>The actual PDF has not been provided yet. To avoid a broken download, this viewer will unlock once the verified resume is added.</p><a href={'mailto:'+profile.email} className="button button-gold"><Mail size={16}/> REQUEST RESUME</a></>}</div></motion.div>;}
function App() {
  const reduced=useReducedMotion();
  const [stage,setStage]=useState<'opening'|'profiles'|'home'>(()=>{try{return sessionStorage.getItem('jatin-series-mode')?'home':(window.matchMedia('(prefers-reduced-motion: reduce)').matches?'profiles':'opening');}catch{return 'opening';}});
  const [mode,setMode]=useState<ViewMode>(()=>{try{return (sessionStorage.getItem('jatin-series-mode') as ViewMode)||'explore';}catch{return 'explore';}});
  const [selected,setSelected]=useState<Project|null>(null);const [reel,setReel]=useState(false);const [resume,setResume]=useState(false);
  useEffect(()=>{if(stage==='home')return;const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prev;};},[stage]);
  const choose=(id:ViewMode)=>{setMode(id);try{sessionStorage.setItem('jatin-series-mode',id);}catch{}setStage('home');window.scrollTo(0,0);};
  const navigate=(id:SectionId)=>{document.getElementById(id)?.scrollIntoView({behavior:reduced?'auto':'smooth'});};
  const replay=()=>{setStage('opening');window.scrollTo(0,0);};
  const sections:Record<SectionId,ReactNode>={about:<About/>,journey:<Journey/>,originals:<Originals onSelect={setSelected}/>,skills:<Skills openProject={setSelected}/>,highlights:<Highlights openProject={setSelected}/>,dossier:<Dossier onView={()=>setResume(true)}/>};
  const order=modes.find(m=>m.id===mode)?.order||modes[0].order;
  return <><AnimatePresence mode="wait">{stage==='opening'&&<Opening key="opening" done={()=>setStage('profiles')}/ >}{stage==='profiles'&&<Selector key="profiles" choose={choose}/>}</AnimatePresence>{stage==='home'&&<motion.div className="app-shell" initial={{opacity:0,filter:'blur(8px)'}} animate={{opacity:1,filter:'blur(0)'}} transition={{duration:.8}}><Nav mode={mode} switchMode={choose} replay={replay}/><Hero mode={mode} onIntro={()=>setReel(true)} onWork={()=>navigate('originals')} onResume={()=>setResume(true)}/><main>{order.map(id=><div key={id}>{sections[id]}</div>)}</main><FinalCTA replay={replay}/></motion.div>}<AnimatePresence>{selected&&<ProjectModal key={selected.id} project={selected} close={()=>setSelected(null)} change={setSelected}/>}</AnimatePresence><AnimatePresence>{reel&&<IntroReel close={()=>setReel(false)}/>}</AnimatePresence><AnimatePresence>{resume&&<ResumeModal close={()=>setResume(false)}/>}</AnimatePresence></>;
}
export default App;
